### PR TITLE
[nomerge] Attempt to get a build running in CI

### PR DESCRIPTION
**Pull request by peterbraden**
This isn't ready to be merged, but I'm struggling, and was wondering if anyone had ideas to get this to work.

Basically, it would be great as a first step to get a consistent build running in Travis, so we can start from a good point.

I added tensorflow as a submodule so that we can guarantee a specific version, and so that built files live at a known location within the module.

This all works locally for me, but I haven't yet managed to get the build running on travis.

### CODE REVIEW

**Comment by tngan** [comment]
Hi @peterbraden, I am running the preinstall script locally and encountering the errors as follow:

```
> node-tensorflow@0.0.1 _preinstall /github/node-tensorflow
> git submodule update --init --recursive && ./tools/build.sh

Submodule 'lib/tensorflow' (https://github.com/tensorflow/tensorflow.git) registered for path 'lib/tensorflow'
Cloning into 'lib/tensorflow'...
remote: Counting objects: 17604, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 17604 (delta 1), reused 0 (delta 0), pack-reused 17598
Receiving objects: 100% (17604/17604), 24.91 MiB | 310.00 KiB/s, done.
Resolving deltas: 100% (11809/11809), done.
Checking connectivity... done.
Submodule path 'lib/tensorflow': checked out 'c4207090d68151fb967672a90ea6d574e62cfba0'
Submodule 'google/protobuf' (https://github.com/google/protobuf.git) registered for path 'google/protobuf'
Cloning into 'google/protobuf'...
remote: Counting objects: 30335, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 30335 (delta 12), reused 0 (delta 0), pack-reused 30302
Receiving objects: 100% (30335/30335), 28.82 MiB | 70.00 KiB/s, done.
Resolving deltas: 100% (20280/20280), done.
Checking connectivity... done.
Submodule path 'lib/tensorflow/google/protobuf': checked out 'bc215089ca7d9da3a2b313b250d1dee665eda438'

HEAD is now at c420709 Merge pull request #1050 from chemelnucfin/fixcomparison.
patching file tensorflow/cc/BUILD
No GPU support will be enabled for TensorFlow
Configuration finished
....................................
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:11:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:12:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:11:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:12:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:21:13: Traceback (most recent call last):
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 14
        cc_library(name = "cc_op_gen_main", srcs = ["ops/cc_op_gen.cc", "ops/cc_op_gen_main.cc"], hdrs = ["ops/cc_op_gen.h"], copts = tf_copts(), deps = ["//tensorflow/core:framework"])
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 21, in cc_library
        tf_copts
name 'tf_copts' is not defined.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:28:1: name 'tf_gen_op_wrappers_cc' is not defined.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:66:13: Traceback (most recent call last):
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 63
        cc_binary(name = "tutorials_example_trainer", srcs = ["tutorials/example_trainer.cc"], copts = tf_copts(), linkopts = ["-lpthread", "-lm"], deps = [":cc_ops", "//tensorflow/core:all_kernels", "//tensorflow/core:tensorflow"])
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 66, in cc_binary
        tf_copts
name 'tf_copts' is not defined.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:80:13: Traceback (most recent call last):
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 78
        cc_binary(name = "libtensorflow.so", copts = tf_copts(), linkshared = 1, linkopts = ["-lpthread", "-lm"], deps = [":cc_ops", "//tensorflow/core:all_kernels", "//tensorflow/core:tensorflow"])
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 80, in cc_binary
        tf_copts
name 'tf_copts' is not defined.
ERROR: no such target '//tensorflow/cc:libtensorflow.so': target 'libtensorflow.so' not declared in package 'tensorflow/cc' defined by /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD.
INFO: Elapsed time: 1.973s
```

**Comment by tngan** [comment]
Hi @peterbraden , instead of merging to master branch, would you like to create anther PR to the new branch `install/ci` ? I have already configured this repository with Travis CI.

**Comment by peterbraden** [comment]
Interesting, haven't seen that error before - which version of Bazel do you have?

I can't change the destination for the PR, but I can close it and open a new one.

**Comment by peterbraden** [comment]
https://github.com/node-tensorflow/node-tensorflow/pull/9 Here

**Pull request closed without merging**
